# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zedstep
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todo-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-serverless

provider:
  name: aws
  runtime: nodejs20.x
  profile: sls
  region: eu-north-1
  stage: dev

functions:
  listTodos:
    handler: functions/todo/list.handler
    name: list-todos-${sls:stage}
    description: Return list of todos
    events:
      - httpApi:
          path: /todos
          method: get

#resources:
#  Resources:
#    TodosDb:
#      Properties:
#        TableName: ${self:provider.environment.TODOS_DB}
#        AttributeDefinitions:
#          - AttributeName: pk
#            AttributeType: S
#          - AttributeName: sk
#            AttributeType: S
#        KeySchema:
#          - AttributeName: pk
#            KeyType: HASH
#          - AttributeName: sk
#            KeyType: SORT
#        BillingMode: PAY_PER_REQUEST